### ISSUE TITLE
Which settings to import for canDrawOverlays? 

### ISSUE THREAD

**Issue by Binzzzz** [marshallino16/Demo-FloatingView#8]
While compiling the project I'm getting a problem with the Settings which is showing a mismatch. Could you suggest which settings should i use?
Error:(84, 8) error: cannot find symbol variable Settings

**Comment by iballan** [comment]
you should first check if the target sdk of your project is Android M, In your case the target api is not Marshmallow, thats why you see this error.
then check whether the android build version sdk_int >= Marshmallow before calling canDrawOverlays

canDrawOverlays provided in Marshmallow though

**Comment by searchy2** [comment]
Change target SDK to Android M. Wrap canDrawOverlays with build version check. 
PR #9 solves this issue. Once the PR is approved, this issue can be closed.

**Comment by marshallino16** [comment]
Thanks for the PR @searchy2
